### PR TITLE
Fixing some simple linting errors with the .md files

### PR DESCRIPTION
**Pull request by ryan-thorburn**

### CODE REVIEW

**Comment by brianorwhatever** [comment]
Two linting changes that stood out to me:
1. Replacing the <br/> with \ I'm not confident is the right approach. I tested this in a few different markdown interpreters with mixed results.. I do know that markdown wants an empty line to signify a line break so that would work 100% of the time.
2. Adding the angle brackets around a few links.. This seems fine in principal but just raises an eyebrow for me. One of the interpreters I used just hides angle bracketed text? 🤨

I _think_ these pages are only used for testing this tool? so not a big deal I would think regardless.

**Comment by brianorwhatever** [comment]
lets remove the <br/> change and I think we can just merge the rest in

**Comment by RieksJ** [comment]
The idea (as specified in the specs) is that frontmatter of a curated text is copied 1-1 into an MRG entry (after which some changes might be made, but that should not include any formatting changes). Testing can be done, e.g. using the curated texts associated with the TEv2 specs. There is a [saf.yaml file](https://github.com/essif-lab/framework/blob/master/docs/tev2/saf.yaml) that points to the [location of the TEv2 terms](https://github.com/essif-lab/framework/tree/master/docs/tev2/terms).  Does that help?

**Comment by brianorwhatever** [comment]
Let's see how the carriage return works out

**Pull request merged**
